### ISSUE TITLE
It is not working

### ISSUE THREAD

**Issue by sparkshares** [m-ler/youtube-clone#1]
Hello brother, 
I cloned the repo, did npm install,
Then also updated it with youtube api,

but still it is not working, no data is showing, what went wrong can you help me?

![image](https://github.com/m-ler/youtube-clone/assets/123289411/83710d26-2807-4145-901f-2c345b74b069)

**Comment by m-ler** [comment]
Hey there, sorry for the late reply. 

Did you make sure your Youtube API key is valid?  
You should see an error in the Next.Js terminal telling you what exactly happened.

I'm still working on this project so it probably has some more errors.
